# config.yaml
# Edit this file to set your trading configuration

tickers:
  - AAPL
  #- TSLA
  #- NVDA
start_date: '2020-01-01'
end_date: '2023-01-01'
initial_cash: 100000
risk_free_rate: 0.0
# Add strategy params
sma_window: 5
