## Trading System Configuration (Cleaned)

# Basic Settings
tickers: [AAPL]
start_date: '2022-01-01'
end_date: '2023-12-31'
initial_cash: 100000
risk_free_rate: 0.0
commission: 0.001

# Portfolio Allocation
portfolio_allocation:
  long_term: 0.50
  short_term: 0.20
  talib: 0.15
  day_trading: 0.10
  options: 0.05

# Strategy configurations moved to per-strategy YAML overlay files:
#   strategy_long_term.yaml, strategy_short_term.yaml, strategy_talib.yaml, strategy_options.yaml
# This base file now only holds global/shared settings & portfolio allocation.
strategies:
  long_term:
    enabled: true
  short_term:
    enabled: true
  talib:
    enabled: true
  day_trading:
    enabled: true
  options:
    enabled: false

# Global Risk Management
risk_management:
  max_portfolio_drawdown: 0.15
  portfolio_var_limit: 0.02
  correlation_threshold: 0.75
  rebalance_frequency: monthly

# Volume (shared)
volume:
  obv_ma_window: 20
  mfi_period: 14
  mfi_oversold: 20
  mfi_overbought: 80
  cmf_fast_period: 3
  cmf_slow_period: 10
  vwap_period: D
  volume_profile_bins: 12
  institutional_volume_threshold: 1000000
  volume_breakout_mult: 2.0
  adl_ma_window: 50
  vpt_change_threshold: 0.02

# Data Cache Settings
data_cache:
  enable: true
  force_refresh: false
  format: parquet
  dir: data/cache
  auto_adjust: true
  ttl_days: 7

# Visualization Settings
visualization:
  generate_charts: true
  output_dir: charts
